### ISSUE TITLE
Ammunition Without Rarity

### ISSUE THREAD

**Issue by illcom94** [NekroDarkmoon/ammo-tracker-fvtt#16] opened 2022-10-25 00:10 UTC
If the ammunition doesn't have a rarity assigned, it isn't tracked. It's not a huge issue, but D&D Beyond Imported doesn't assign rarity to mundane items because they don't have rarity assign by RAW.

**Comment by NekroDarkmoon** [comment] 2022-10-27 14:19
Fixed in 0.3.1

**Comment by illcom94** [comment] 2022-11-03 22:01
This doesn't seem to work for me anymore. I'm getting a console error at the end of combat.
dnd5e.js:49 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Lda7LHMxbAQpV2k4')
[Detected 1 package: ammo-tracker-fvtt]
    at Dnd5eTracker.usedAmmo (dnd5e.js:49:35)
    at Dnd5eTracker.endTracker (AmmoTracker.js:42:26)
etc....

**Comment by NekroDarkmoon** [comment] 2022-11-03 22:05
Can i get the full error log?

**Comment by illcom94** [comment] 2022-11-03 22:18
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Lda7LHMxbAQpV2k4')
[Detected 1 package: ammo-tracker-fvtt]
    at Dnd5eTracker.usedAmmo (dnd5e.js:49:35)
    at Dnd5eTracker.endTracker (AmmoTracker.js:42:26)
    at Object.fn (index.js:74:19)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12886:13)
    at foundry.js:12836:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleDeleteDocuments (foundry.js:12836:33)
    at ClientDatabaseBackend._deleteDocuments (foundry.js:12743:17)
    at async Combat.deleteDocuments (commons.js:6165:23)
    at async Combat.delete (commons.js:6232:23)
    at async MonksCombatTracker._onCombatControl (foundry.js:74342:15)
usedAmmo @ dnd5e.js:49
endTracker @ AmmoTracker.js:42
(anonymous) @ index.js:74
#call @ foundry.js:724
callAll @ foundry.js:681
callback @ foundry.js:12886
(anonymous) @ foundry.js:12836
_handleDeleteDocuments @ foundry.js:12836
_deleteDocuments @ foundry.js:12743

**Comment by illcom94** [comment] 2022-11-04 15:29
I've verified if I roll back to 3.0 it works again. (with rarity assigned of course).

**Comment by KenGitsIt** [comment] 2022-11-12 07:57
The issue is that len() is not a Javascript function in line 109 of dnd5e.js.  The line
```i => i.system.rarity === 'common' || len(i.system.rarity) === 0```
should be
```i => i.system.rarity === 'common' || i.system.rarity.length === 0```

**Comment by NekroDarkmoon** [comment] 2022-11-16 01:17
> 

Yeah it was the incorrect usage of len() instead of length.

**Closed** 2022-11-16 01:19 UTC
Labels: bug
